#!/bin/sh
## Generate debug executable
RELEASE="../build/release"
DEBUG="../build/debug"

if [ ! -d "$RELEASE" ] ; then
    mkdir -p "$RELEASE"
fi


if [ ! -d "$DEBUG" ] ; then
    mkdir -p "$DEBUG"
fi

## Generate release executable
cd "$DEBUG"
cmake -DCMAKE_BUILD_TYPE=Debug ../..
make install -j8
